import { stringifyOpenMaintainerConfig } from "@open-maintainer/config";
import type { GeneratedArtifact, RepoProfile } from "@open-maintainer/shared";
import { newId, nowIso } from "@open-maintainer/shared";

export type StructuredContextOutput = {
  summary: string;
  qualityRules: string[];
  commands: string[];
  notes: string[];
};

export function renderAgentsMd(
  profile: RepoProfile,
  output: StructuredContextOutput,
): string {
  const commands =
    output.commands.length > 0
      ? output.commands
      : profile.commands.map(
          (command) => `${command.name}: ${command.command}`,
        );
  return [
    `# AGENTS.md instructions for ${profile.owner}/${profile.name}`,
    "",
    "## Repository Summary",
    "",
    output.summary,
    "",
    "## Quality Rules",
    "",
    ...output.qualityRules.map((rule) => `- ${rule}`),
    "",
    "## Commands",
    "",
    ...commands.map((command) => `- ${command}`),
    "",
    "## Evidence",
    "",
    ...profile.evidence.map((item) => `- ${item.path}: ${item.reason}`),
    "",
    "<!-- generated by open-maintainer; edit through .open-maintainer.yml after merge -->",
  ].join("\n");
}

export function renderOpenMaintainerYaml(
  profile: RepoProfile,
  artifactVersion: number,
  rules: string[],
): string {
  return stringifyOpenMaintainerConfig({
    version: 1,
    repo: {
      profileVersion: profile.version,
      defaultBranch: profile.defaultBranch,
    },
    rules,
    generated: {
      by: "open-maintainer",
      artifactVersion,
      generatedAt: nowIso(),
    },
  });
}

export function createContextArtifacts(input: {
  repoId: string;
  profile: RepoProfile;
  output: StructuredContextOutput;
  modelProvider: string | null;
  model: string | null;
  nextVersion: number;
}): GeneratedArtifact[] {
  const createdAt = nowIso();
  const agentsVersion = input.nextVersion;
  const configVersion = input.nextVersion + 1;
  return [
    {
      id: newId("artifact"),
      repoId: input.repoId,
      type: "AGENTS.md",
      version: agentsVersion,
      content: renderAgentsMd(input.profile, input.output),
      sourceProfileVersion: input.profile.version,
      modelProvider: input.modelProvider,
      model: input.model,
      createdAt,
    },
    {
      id: newId("artifact"),
      repoId: input.repoId,
      type: ".open-maintainer.yml",
      version: configVersion,
      content: renderOpenMaintainerYaml(
        input.profile,
        configVersion,
        input.output.qualityRules,
      ),
      sourceProfileVersion: input.profile.version,
      modelProvider: input.modelProvider,
      model: input.model,
      createdAt,
    },
  ];
}

export function deterministicContextOutput(
  profile: RepoProfile,
): StructuredContextOutput {
  return {
    summary: `${profile.owner}/${profile.name} is a ${profile.primaryLanguages.join(", ") || "software"} repository on ${profile.defaultBranch}.`,
    qualityRules:
      profile.reviewRuleCandidates.length > 0
        ? profile.reviewRuleCandidates
        : [
            "Read target files before editing.",
            "Run the documented quality gates before finishing.",
          ],
    commands: profile.commands.map(
      (command) => `${command.name}: ${command.command}`,
    ),
    notes: profile.detectedRiskAreas,
  };
}
