import { createHash } from "node:crypto";
import { stringifyOpenMaintainerConfig } from "@open-maintainer/config";
import type {
  ArtifactType,
  GeneratedArtifact,
  RepoProfile,
} from "@open-maintainer/shared";
import { newId, nowIso } from "@open-maintainer/shared";
import { z } from "zod";

export const StructuredContextOutputSchema = z.object({
  summary: z.string().min(1),
  qualityRules: z.array(z.string().min(1)),
  commands: z.array(z.string().min(1)),
  notes: z.array(z.string().min(1)),
});
export type StructuredContextOutput = z.infer<
  typeof StructuredContextOutputSchema
>;

export type ContextArtifactTarget =
  | "agents"
  | "copilot"
  | "cursor"
  | "skills"
  | "profile"
  | "report"
  | "config";

export const defaultArtifactTargets: ContextArtifactTarget[] = [
  "agents",
  "copilot",
  "cursor",
  "skills",
  "profile",
  "report",
  "config",
];

export type ArtifactWritePlanItem = {
  artifact: GeneratedArtifact;
  path: string;
  action: "write" | "skip" | "overwrite";
  reason: string;
};

const generatedMarker = "generated by open-maintainer";

export function renderAgentsMd(
  profile: RepoProfile,
  output: StructuredContextOutput,
): string {
  const commands =
    output.commands.length > 0 ? output.commands : commandLines(profile);
  return [
    `# AGENTS.md instructions for ${profile.owner}/${profile.name}`,
    "",
    `<!-- ${metadataComment(profile)} -->`,
    "",
    "## Repository Purpose",
    "",
    output.summary,
    "",
    "## Setup and Quality Commands",
    "",
    ...commands.map((command) => `- ${command}`),
    "",
    "## Architecture Map",
    "",
    ...listOrFallback(
      profile.architecturePathGroups.map(
        (group) => `${group}: detected subsystem path`,
      ),
      "No major subsystem paths were detected.",
    ),
    "",
    "## Generated and Sensitive Paths",
    "",
    ...profile.generatedFileHints.map((hint) => `- ${hint}`),
    "",
    "## Risk Areas",
    "",
    ...listOrFallback(
      output.notes,
      "No deterministic risk hints were detected.",
    ),
    "",
    "## Quality Rules",
    "",
    ...output.qualityRules.map((rule) => `- ${rule}`),
    "",
    "## PR Expectations",
    "",
    "- Read the target file and a related caller, test, or type before editing.",
    "- Keep generated artifacts scoped to the approved paths.",
    "- Run the relevant quality gates and include failures or skipped checks in the handoff.",
    "",
    "## Common Mistakes to Avoid",
    "",
    "- Do not overwrite maintainer-owned context files without an explicit force decision.",
    "- Do not send repository content to a model provider unless repo-content consent is enabled.",
    "- Do not commit directly to the default branch from automated PR flows.",
    "",
    "## Evidence",
    "",
    ...profile.evidence.map((item) => `- ${item.path}: ${item.reason}`),
    "",
    `<!-- ${generatedMarker}; edit through .open-maintainer.yml after merge -->`,
  ].join("\n");
}

export function renderOpenMaintainerYaml(
  profile: RepoProfile,
  artifactVersion: number,
  rules: string[],
): string {
  return stringifyOpenMaintainerConfig({
    version: 1,
    repo: {
      profileVersion: profile.version,
      defaultBranch: profile.defaultBranch,
    },
    rules,
    generated: {
      by: "open-maintainer",
      artifactVersion,
      generatedAt: nowIso(),
    },
  });
}

export function renderCopilotInstructions(
  profile: RepoProfile,
  output: StructuredContextOutput,
): string {
  return [
    `# Copilot instructions for ${profile.owner}/${profile.name}`,
    "",
    `<!-- ${metadataComment(profile)} -->`,
    "",
    output.summary,
    "",
    "## Commands",
    "",
    ...commandLines(profile).map((command) => `- ${command}`),
    "",
    "## Review Rules",
    "",
    ...output.qualityRules.map((rule) => `- ${rule}`),
  ].join("\n");
}

export function renderCursorRule(
  profile: RepoProfile,
  output: StructuredContextOutput,
): string {
  return [
    "---",
    "description: Open Maintainer generated repository rules",
    "alwaysApply: true",
    "---",
    "",
    `# ${profile.owner}/${profile.name}`,
    "",
    `<!-- ${metadataComment(profile)} -->`,
    "",
    output.summary,
    "",
    "Use these commands when they apply:",
    "",
    ...commandLines(profile).map((command) => `- ${command}`),
    "",
    "Follow these review rules:",
    "",
    ...output.qualityRules.map((rule) => `- ${rule}`),
  ].join("\n");
}

export function renderSkill(
  profile: RepoProfile,
  name: "repo-overview" | "testing-workflow" | "pr-review",
  output: StructuredContextOutput,
): string {
  const title = name
    .split("-")
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
  const description =
    name === "repo-overview"
      ? `Use when working in ${profile.owner}/${profile.name}; summarizes architecture, commands, generated files, and risk areas.`
      : name === "testing-workflow"
        ? `Use when changing tests or running validation in ${profile.owner}/${profile.name}.`
        : `Use when preparing or reviewing pull requests in ${profile.owner}/${profile.name}.`;
  return [
    "---",
    `name: ${name}`,
    `description: ${description}`,
    "---",
    "",
    `# ${title}`,
    "",
    `<!-- ${metadataComment(profile)} -->`,
    "",
    output.summary,
    "",
    "## Commands",
    "",
    ...commandLines(profile).map((command) => `- ${command}`),
    "",
    "## Rules",
    "",
    ...output.qualityRules.map((rule) => `- ${rule}`),
    "",
    "## Evidence",
    "",
    ...profile.evidence
      .slice(0, 20)
      .map((item) => `- ${item.path}: ${item.reason}`),
  ].join("\n");
}

export function renderReadinessReport(profile: RepoProfile): string {
  return [
    `# Open Maintainer Report: ${profile.owner}/${profile.name}`,
    "",
    `Agent Readiness: ${profile.agentReadiness.score}/100`,
    "",
    "## Category Scores",
    "",
    ...profile.agentReadiness.categories.flatMap((category) => [
      `### ${category.name}: ${category.score}/${category.maxScore}`,
      "",
      ...(category.missing.length > 0
        ? category.missing.map((item) => `- Missing: ${item}`)
        : ["- No missing items detected."]),
      ...category.evidence.map(
        (item) => `- Evidence: ${item.path} (${item.reason})`,
      ),
      "",
    ]),
    "## Commands",
    "",
    ...listOrFallback(commandLines(profile), "No commands detected."),
    "",
    "## Architecture",
    "",
    ...listOrFallback(
      profile.architecturePathGroups,
      "No architecture paths detected.",
    ),
    "",
    "## Risk Hints",
    "",
    ...listOrFallback(
      profile.detectedRiskAreas,
      "No deterministic risk hints detected.",
    ),
  ].join("\n");
}

export function createContextArtifacts(input: {
  repoId: string;
  profile: RepoProfile;
  output: StructuredContextOutput;
  modelProvider: string | null;
  model: string | null;
  nextVersion: number;
  targets?: ContextArtifactTarget[];
}): GeneratedArtifact[] {
  const createdAt = nowIso();
  const targets = new Set(input.targets ?? defaultArtifactTargets);
  const definitions: Array<{ type: ArtifactType; content: string }> = [];
  if (targets.has("agents")) {
    definitions.push({
      type: "AGENTS.md",
      content: renderAgentsMd(input.profile, input.output),
    });
  }
  if (targets.has("config")) {
    definitions.push({
      type: ".open-maintainer.yml",
      content: renderOpenMaintainerYaml(
        input.profile,
        input.nextVersion + definitions.length,
        input.output.qualityRules,
      ),
    });
  }
  if (targets.has("copilot")) {
    definitions.push({
      type: ".github/copilot-instructions.md",
      content: renderCopilotInstructions(input.profile, input.output),
    });
  }
  if (targets.has("cursor")) {
    definitions.push({
      type: ".cursor/rules/open-maintainer.md",
      content: renderCursorRule(input.profile, input.output),
    });
  }
  if (targets.has("skills")) {
    definitions.push(
      {
        type: ".skills/repo-overview/SKILL.md",
        content: renderSkill(input.profile, "repo-overview", input.output),
      },
      {
        type: ".skills/testing-workflow/SKILL.md",
        content: renderSkill(input.profile, "testing-workflow", input.output),
      },
      {
        type: ".skills/pr-review/SKILL.md",
        content: renderSkill(input.profile, "pr-review", input.output),
      },
    );
  }
  if (targets.has("profile")) {
    definitions.push({
      type: ".open-maintainer/profile.json",
      content: `${JSON.stringify(
        {
          ...input.profile,
          openMaintainerProfileHash: profileFingerprint(input.profile),
        },
        null,
        2,
      )}\n`,
    });
  }
  if (targets.has("report")) {
    definitions.push({
      type: ".open-maintainer/report.md",
      content: renderReadinessReport(input.profile),
    });
  }

  return definitions.map((definition, index) => ({
    id: newId("artifact"),
    repoId: input.repoId,
    type: definition.type,
    version: input.nextVersion + index,
    content: definition.content,
    sourceProfileVersion: input.profile.version,
    modelProvider: input.modelProvider,
    model: input.model,
    createdAt,
  }));
}

export function deterministicContextOutput(
  profile: RepoProfile,
): StructuredContextOutput {
  return {
    summary: `${profile.owner}/${profile.name} is a ${profile.primaryLanguages.join(", ") || "software"} repository on ${profile.defaultBranch}. Detected subsystems: ${profile.architecturePathGroups.join(", ") || "none"}.`,
    qualityRules:
      profile.reviewRuleCandidates.length > 0
        ? profile.reviewRuleCandidates
        : [
            "Read target files before editing.",
            "Run the documented quality gates before finishing.",
          ],
    commands: commandLines(profile),
    notes: profile.detectedRiskAreas,
  };
}

export function buildContextSynthesisPrompt(profile: RepoProfile): {
  system: string;
  user: string;
} {
  return {
    system:
      "Return only valid JSON matching {summary:string,qualityRules:string[],commands:string[],notes:string[]}. Do not include markdown fences.",
    user: JSON.stringify({
      repo: `${profile.owner}/${profile.name}`,
      languages: profile.primaryLanguages,
      frameworks: profile.frameworks,
      commands: profile.commands,
      architecturePathGroups: profile.architecturePathGroups,
      evidence: profile.evidence,
      riskAreas: profile.detectedRiskAreas,
    }),
  };
}

export function parseStructuredContextOutput(
  text: string,
): StructuredContextOutput {
  const parsed = JSON.parse(text) as unknown;
  return StructuredContextOutputSchema.parse(parsed);
}

export function profileFingerprint(profile: RepoProfile): string {
  return createHash("sha256")
    .update(
      JSON.stringify({
        owner: profile.owner,
        name: profile.name,
        defaultBranch: profile.defaultBranch,
        commands: profile.commands,
        docs: profile.importantDocs,
        paths: profile.architecturePathGroups,
      }),
    )
    .digest("hex")
    .slice(0, 16);
}

export function planArtifactWrites(input: {
  artifacts: GeneratedArtifact[];
  existingPaths: Set<string>;
  force?: boolean;
}): ArtifactWritePlanItem[] {
  return input.artifacts.map((artifact) => {
    const exists = input.existingPaths.has(artifact.type);
    if (!exists) {
      return {
        artifact,
        path: artifact.type,
        action: "write",
        reason: "file is absent",
      };
    }
    if (input.force) {
      return {
        artifact,
        path: artifact.type,
        action: "overwrite",
        reason: "force enabled",
      };
    }
    return {
      artifact,
      path: artifact.type,
      action: "skip",
      reason: "existing file preserved; rerun with --force to overwrite",
    };
  });
}

function commandLines(profile: RepoProfile): string[] {
  return profile.commands.map(
    (command) => `${command.name}: ${command.command} (${command.source})`,
  );
}

function listOrFallback(items: string[], fallback: string): string[] {
  return items.length > 0
    ? items.map((item) => `- ${item}`)
    : [`- ${fallback}`];
}

function metadataComment(profile: RepoProfile): string {
  return `${generatedMarker}; sourceProfileVersion=${profile.version}; profileHash=${profileFingerprint(profile)}`;
}
