import { describe, expect, it } from "vitest";
import {
  contextArtifactSlug,
  contextArtifactTargetsForSelection,
  expectedContextArtifactTypes,
  isContextArtifactPath,
  isOpenMaintainerGeneratedContent,
  obsoleteGeneratedContextArtifactPaths,
  selectWritableContextArtifacts,
} from "../src";
import type { GeneratedArtifact } from "../src";

describe("context artifact registry", () => {
  it("derives expected paths and writable artifacts from one registry", () => {
    const expected = expectedContextArtifactTypes({
      repoName: "---Open    Maintainer---Agent---",
      targets: ["agents", "skills", "claude-skills", "profile", "report"],
    });

    expect(expected).toEqual([
      "AGENTS.md",
      ".agents/skills/open-maintainer-agent-start-task/SKILL.md",
      ".agents/skills/open-maintainer-agent-testing-workflow/SKILL.md",
      ".agents/skills/open-maintainer-agent-pr-review/SKILL.md",
      ".claude/skills/open-maintainer-agent-start-task/SKILL.md",
      ".claude/skills/open-maintainer-agent-testing-workflow/SKILL.md",
      ".claude/skills/open-maintainer-agent-pr-review/SKILL.md",
      ".open-maintainer/profile.json",
      ".open-maintainer/report.md",
    ]);

    const artifacts = [
      artifact("repo_profile", 1),
      artifact("AGENTS.md", 2),
      artifact(".agents/skills/open-maintainer-agent-pr-review/SKILL.md", 3),
    ];

    expect(selectWritableContextArtifacts(artifacts)).toEqual([
      { artifact: artifacts[1], path: "AGENTS.md" },
      {
        artifact: artifacts[2],
        path: ".agents/skills/open-maintainer-agent-pr-review/SKILL.md",
      },
    ]);
  });

  it("classifies generated content, context paths, selections, and obsolete skills", () => {
    expect(contextArtifactSlug("  Open Maintainer  Agent  ")).toBe(
      "open-maintainer-agent",
    );
    expect(isContextArtifactPath("AGENTS.md")).toBe(true);
    expect(
      isContextArtifactPath(".agents/skills/tool-pr-review/SKILL.md"),
    ).toBe(true);
    expect(isContextArtifactPath("repo_profile")).toBe(false);
    expect(
      isOpenMaintainerGeneratedContent(
        "generated:\n  by: open-maintainer\n  artifactVersion: 2\n",
      ),
    ).toBe(true);
    expect(
      contextArtifactTargetsForSelection({
        context: "both",
        skills: "claude",
      }),
    ).toEqual([
      "agents",
      "claude",
      "claude-skills",
      "profile",
      "report",
      "config",
    ]);
    expect(
      obsoleteGeneratedContextArtifactPaths({
        generatedPaths: new Set([
          ".agents/skills/tool-old/SKILL.md",
          ".claude/skills/tool-old/SKILL.md",
          "AGENTS.md",
        ]),
        artifactPaths: new Set([".agents/skills/tool-new/SKILL.md"]),
        targets: ["skills"],
      }),
    ).toEqual([".agents/skills/tool-old/SKILL.md"]);
  });
});

function artifact(
  type: GeneratedArtifact["type"],
  version: number,
): GeneratedArtifact {
  return {
    id: `artifact_${version}`,
    repoId: "repo_1",
    type,
    version,
    content: "# generated by open-maintainer\n",
    sourceProfileVersion: 1,
    modelProvider: null,
    model: null,
    createdAt: "2026-04-30T00:00:00.000Z",
  };
}
